= DayCaptain's REST API _(first draft)_

https://daycaptain.com[DayCaptain^] offers a REST API to manager a user's information objects.

The API is usable with any technology that supports HTTP.

An example call that creates a new day task looks as follows (with `curl`):

----
curl 'https://daycaptain.com/2021-12-31/tasks' \
  -XPOST -i \
  -H "Authorization: Bearer <token>" \
  -H 'Content-Type: application/json' \
  -d '{"string":"Hello Captain"}'
----

== Authentication

To authenticate your user in the API calls, you have to include a `Bearer` token.

You generate a token in your https://daycaptain.com/account.html[user account^] (`G+X`) under the section _API Tokens_.
The generated token is used as the `Bearer` token in the `Authorization` HTTP header, as seen above.

*Example:*

"Your token: `123[..]abc` " + 
will be included as `-H "Authorization: Bearer 123[..]abc"` in your HTTP call.


== Create inbox tasks

You add a tasks that shows up in your https://daycaptain.com/backlogs.html[backlogs^] inbox with the following HTTP call:

This is very helpful for quickly adding tasks that pop up in your head.
By using this way, you don't have to open up the program and you won't get distracted by all the information.

----
curl 'https://daycaptain.com/backlog-items' \
  -XPOST -i \
  -H "Authorization: Bearer <token>" \
  -H 'Content-Type: application/json' \
  -d '{"string":"Hello Captain"}'
----

You can add following information in the request body JSON:

[frame="none",grid="none"]
|=======================================================================================================================
| *Parameter* | *Description*                         | *Example*
| `string`    | Task name (mandatory)                 | `"string": "Hello Captain"`
| `backlog`   | Backlog where to add (inbox if empty) | `"backlog": "To-contact"`
| `note`      | Additional note                       | `"note": "This is a note containing a link\nhttps://google.com"`
| `area`      | Task's area                           | `"area": "Work"`
| `project`   | Task's project                        | `"area": "My side-hustle"`
|=======================================================================================================================

Note that you can either set an `area` or a `project`.
